[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/fitbuddy-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
SPRING_PROFILES_ACTIVE = "production"